import streamlit as st
st.set_page_config(page_title="McKinsey Engine", layout="wide")
st.title("McKinsey Research Engine - Agentic Workflow")
st.caption("7-Agent System: Planner -> Browser -> Extractor -> Validator -> Aggregation -> Memory -> Reporter")
query = st.text_input("Enter research topic", "EV battery recycling in India")
if st.button("Start Agentic Research", type="primary"):
    st.divider()
    st.subheader("1. Planner Agent - Query Decomposition")
    st.write(f"Breaking down: {query}")
    st.success("Create 3 tracks: Market Size, Competitors, Regulations")
    st.subheader("2. Browser Agent - Tavily Search")
    st.info("Searching 5 sources per track with URL and Data filter")
    st.code("tavily.search(query, max_results=5, search_depth='advanced')")
    st.subheader(""3. Extractor Agent - Evidence Extraction")
    st.json({"claim": "EV market $1.2B by 2030", "source": "reuters.com", "date": "2024-08-01", "https://reuters.com?..."})
    st.subheader("4. Validator Agent" - 3 Checks")
    st.write("Credibility: reuters.com = Trusted")
    st.write("Recency: 2024 = Fresh")
    st.write("Duplicate: Unique")
    st.success("Validation PASSED")
    st.subheader("5. Aggregation Agent")
    st.write("Grouped 15 evidences into 3 themes")
    st.subheader("6. Memory Agent - ChromaDB")
    st.code("chroma_collection.add(documents=[framework"])")
    st.write("Saved to memory")
    st.subheader("7. Report Agent - Final Report with Citations")
    st.markdown(f"### Report: {query}\nMarket $1.2B by 2030 [Source: reuters.com]\nCompetitors 3 players [Source: gov.in]\nRegulations 2024 Rules [Source: mckinsey.com]\n\nHuman-Review Note: Cross-check figures, \n\nCitations: [1] reuters.com, [2] gov.in")
    st.balloons()           

